### Get user by id
GET http://localhost:3000/users/11


### Create new user in north hemisphere
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "jlurbe",
  "email": "juanjo.lurbe@gmail.com",
  "password": "123456", 
  "longitude": -0.3295, 
  "latitude": 39.6018, 
  "browserLanguage": "en"
}

### Create new user in south hemisphere
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "jlurbe",
  "email": "jlurbe@gmail.com",
  "password": "123456", 
  "longitude": 120.12234, 
  "latitude": -20.34789, 
  "browserLanguage": "es"
}

### Update user in north hemisphere
PUT http://localhost:3000/users/11
Content-Type: application/json

{
  "username": "juan.lurbe",
  "email": "juanjo.lurbe@gmail.com",
  "password": "123456", 
  "longitude": -0.3295, 
  "latitude": 39.6018, 
  "browserLanguage": "es"
}

### Update user in south hemisphere
PUT http://localhost:3000/users/3
Content-Type: application/json

{
  "username": "jlurbe",
  "email": "jlurbe@gmail.com",
  "password": "123456", 
  "longitude": -0.3295, 
  "latitude": 39.6018, 
  "browserLanguage": "es"
}

### Delete user by id
DELETE http://localhost:3000/users/30
