export enum ErrorCodes {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_CREATED_USER = 'NOT_CREATED_USER',
  NOT_DELETED_USER = 'NOT_DELETED_USER',
  NOT_UPDATED_USER = 'NOT_UPDATED_USER',
  USER_ID_NOT_FOUND = 'USER_ID_NOT_FOUND',
  USER_NOT_RETRIEVED = 'USER_NOT_RETRIEVED',
  NOT_VALIDATED_INFO = 'NOT VALIDATED INFO',
}
